# Generated by Django 3.1.2 on 2021-02-11 22:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_with_spotify', models.BooleanField(default=False)),
                ('list_of_buildings', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0), size=9)),
            ],
        ),
    ]
