# Generated by Django 3.1.2 on 2021-02-11 23:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210211_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='list_of_buildings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0, 0, 0, 0, 0, 0, 0, 0], size=9),
        ),
    ]
