# Generated by Django 3.1.2 on 2021-02-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210212_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='list_of_buildings',
            field=models.JSONField(default=list),
        ),
    ]
